const List<String> serviceTypesList = ['mechanic', 'garage', 'towing'];

const List<String> countriesList = ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'];

const List<String> kenyanCitiesList = [
  'Nairobi',
  'Mombasa',
  'Kisumu',
  'Nakuru',
  'Eldoret',
  'Thika',
  'Malindi',
  'Kitale',
  'Kakamega',
  'Nyeri',
  'Machakos',
  'Embu',
  'Kericho',
  'Bungoma',
  'Busia',
  'Garissa',
  'Homa Bay',
  'Isiolo',
  'Kajiado',
  'Kiambu',
  'Kilifi',
  'Kirinyaga',
  'Kisii',
  'Kitui',
  'Kwale',
  'Laikipia',
  'Lamu',
  'Makueni',
  'Mandera',
  'Marsabit',
  'Meru',
  'Migori',
  'Murang\'a',
  'Nandi',
  'Narok',
  'Nyamira',
  'Nyandarua',
  'Samburu',
  'Siaya',
  'Taita Taveta',
  'Tana River',
  'Trans Nzoia',
  'Turkana',
  'Uasin Gishu',
  'Vihiga',
  'Wajir',
  'West Pokot',
];
